#Importing relevant modules
import random
import time

#Card Class, which will act as the parent class for the player and enemy class
class Card:
  def __init__(self):
    self.card = None
    self.hand = []
    self.no = 0
    self.dealhand = []
    self.dealHandfull = []
    self.playerHandfull = []

  """ The random generator, which will generate a random card """

  def randomgenerator(self):
    self.suit = random.choice(["Hearts", "Diamonds", "Spades", "Clubs"])
    self.no = random.randint(1,11)
    self.card = (f"{self.no} of {self.suit}")
    return(self.card)

#NOTE: THE REMAINING METHODS IN THIS CLASS WILL BE USED IN OTHER METHODS/FUNCTIONS
  """ Report number, which will report the number generated by the randomgenerator """

  def reportNumber(self):
    return(self.no)

  """ The playerHand method, which will return the current deck the player has """

  def playerHand(self):
    return(self.hand)

  """ The dealHand method, which will report the current dealer deck """

  def dealHand(self):
    return(self.dealhand)

  """ The dealHandwithsuits method, which will report the dealer deck and the suites
      for results """

  def dealHandwithsuits(self):
    return(self.dealHandfull)

  """ The playerHandwithsuits method, which will report the player's deck and the suites
      for results """

  def playerHandwithsuits(self):
    return(self.playerHandfull)

#Player Class, child class of card
class Player(Card):
  def __init__(self):
    super().__init__()
    self.name = ' '
    self.hitorstay = None

  """ playername method, which will ask user what their name is """

  def playername(self):
      self.name = input("What is your name?")
      return(self.name)

  """ cardornot, which will prompt user (after deck has been drawn) to hit or stay """
  """ the output of which is an optional parameter for the deck function/method """

  def cardornot(self):
    while self.hitorstay == None or not "hit" or "stay":
      self.hitorstay = input("Hit or stay?").lower()
      if self.hitorstay == "hit":
          return (self.hitorstay)
          break
      if self.hitorstay == "stay":
          return (self.hitorstay)
          break
      else:
          print("Not a valid choice, try again")

  """ deck function for player, which will draw the cards """

  def deck(self, confunction=None):
      if confunction == None:
        while len(self.hand) < 2:
          self.card = self.randomgenerator()
          if len(self.hand) == 1:
            print(f"You drew {self.card}!")
          self.hand.append(self.reportNumber())
          self.playerHandfull.append(self.card)
          time.sleep(1)
      if confunction is not None:
          if confunction == "hit":
            self.card = self.randomgenerator()
            print(f"You drew {self.card}!")
            self.hand.append(self.reportNumber())
            self.playerHandfull.append(self.card)
            return (self.hand)
          if confunction == "stay":
            print ("You have chosen to stay!")
            return (self.hand)

#The Dealer class, which derives from the card class
class Dealer(Card):
    def __init__(self):
      super().__init__()

      self.hitorstay = None

    """ hitorstaydealer, works slightly differently which is why
        it is a different method """

    def hitorstaydealer(self):
      self.hitorstayno = random.randint(1, 11)
      if self.hitorstayno in range(1, 6):
        self.hitorstay = "hit"
        return(self.hitorstay)
      elif sum(self.dealHand()) <= 10:
        self.hitorstay = "hit"
        return(self.hitorstay)
      elif sum(self.dealHand()) >= 21:
        self.hitorstay = "stay"
        return(self.hitorstay)
      else:
        self.hitorstay = "stay"
        return(self.hitorstay)

    """ the dealerdeck, which works similar, but not exactly like the playerdeck """

    def dealerdeck(self, confunctiondealer=None):
        if confunctiondealer == None:
            while len(self.dealhand) < 2:
              self.card = self.randomgenerator()
              self.dealhand.append(self.reportNumber())
              self.dealHandfull.append(self.card)
              time.sleep(1)
              if len(self.dealhand) == 1:
                print(f"The Dealer drew {self.card}!") 
                self.card = self.randomgenerator()
                self.dealhand.append(self.reportNumber())
                self.dealHandfull.append(self.card)
                break
        if confunctiondealer is not None:
              if confunctiondealer == "hit":
                self.card = self.randomgenerator()
                print(f"The Dealer drew {self.card}!")
                self.dealhand.append(self.reportNumber())
                self.dealHandfull.append(self.card)
                return(self.dealhand)
              if confunctiondealer == "stay":
                print ("The Dealer chose to stay!")
                return(self.dealhand)

#The actual BlackJack function
def BlackJack():
  pl = Player()
  dl = Dealer()
  name = 0
  dealerDeck = 0
  playerDeck = 0
  playerSum = 0
  dealerSum = 0
  print("Hello! This is blackjack!")
  print("Rules are simple! Get as close to 21 without going over \n and you win!")
  name = pl.playername()
  print(f"Pleased to meet you, {name}! Now please draw your cards!")

  while True:
    time.sleep(1)
    pl.deck()
    dl.dealerdeck()
    pl.deck(pl.cardornot())
    dl.dealerdeck(dl.hitorstaydealer())
    playerSum = sum(pl.playerHand())
    dealerSum = sum(dl.dealHand())
    dealerDeck = dl.dealHandwithsuits()
    playerDeck = pl.playerHandwithsuits()

    if dealerSum > playerSum and dealerSum < 21:
      print (f"The Dealer had {dealerDeck}")
      print (f"{name} had {playerDeck}")
      print (f"{name} had {playerSum} and the Dealer had {dealerSum}")
      print ("The Dealer has won this game! Better luck next time!")
      break
    elif dealerSum > playerSum and dealerSum > 21:
      print (f"The dealer had {dealerDeck}")
      print (f"{name} had {playerDeck}")
      print (f"{name} had {playerSum} and the Dealer had {dealerSum}")
      print (f"{name} has won this game! Congratulations!")
      break
    elif dealerSum > playerSum and dealerSum == 21:
      print (f"The dealer had {dealerDeck}")
      print (f"{name} had {playerDeck}")
      print (f"{name} had {playerSum} and the Dealer had {dealerSum}")
      print ("The Dealer has won this game! Better luck next time!")
      break
    if playerSum > dealerSum and playerSum < 21:
      print (f"The Dealer had {dealerDeck}")
      print (f"{name} had {playerDeck}")
      print (f"{name} had {playerSum} and the Dealer had {dealerSum}")
      print (f"{name} has won this game! Congratulations!")
      break
    elif playerSum > dealerSum and playerSum > 21:
      print (f"The Dealer had {dealerDeck}")
      print (f"{name} had {playerDeck}")
      print (f"{name} had {playerSum} and the Dealer had {dealerSum}")
      print ("The Dealer has won this game! Better luck next time!")
      break
    elif playerSum > dealerSum and playerSum == 21:
      print (f"The Dealer had {dealerDeck}")
      print (f"{name} had {playerDeck}")
      print (f"{name} had {playerSum} and the Dealer had {dealerSum}")
      print (f"{name} has won this game! Congratulations!")
      break
    if playerSum == dealerSum:
      print ("You and the dealer tied!")
      print (f"{name} had {playerSum} and the Dealer had {dealerSum}")
      print ("Tie breaker!")

BlackJack()
